name: Deploy Website to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout du code
        uses: actions/checkout@v4

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Installation des dépendances
        run: npm install

      - name: 🏗️ Build du projet
        run: npm run build

      - name: 🚀 Déploiement DIRECT
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # ON NE MET RIEN ICI (juste un point) 
          # car ton FTP est déjà dans public_html
          server-dir: ./
          dangerous-clean-slate: true
